# These are the namespace-scoped rbac roles + bindings that will be used by users
# who want to use telepresence once its components have been set
# up in the cluster.
{{- if .Values.clientRbac.create }}
{{- if .Values.clientRbac.namespaced }}

{{- $namespaces := .Values.clientRbac.namespaces }}
{{- $subjects := .Values.clientRbac.subjects }}
{{- range $namespaces }}

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name:  {{ include "telepresence.clientRbacName" $ }}
  namespace: {{ . }}
  labels:
    {{- include "telepresence.labels" $ | nindent 4 }}
rules: 
{{ include "telepresence.clientRbacInterceptRules" $ }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "telepresence.clientRbacName" $ }}
  namespace: {{ . }}
  labels:
    {{- include "telepresence.labels" $ | nindent 4 }}
subjects:
{{- toYaml $subjects | nindent 0}}
roleRef:
  kind: Role
  name: {{ include "telepresence.clientRbacName" $ }}
  apiGroup: rbac.authorization.k8s.io

{{- end }}

{{- end }}

---

# Client must have the following RBAC in the traffic-manager namespace to establish
# a port-forward to the traffic-manager pod.
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name:  traffic-manager-connect
  namespace: {{ include "telepresence.namespace" . }}
  labels:
    {{- include "telepresence.labels" $ | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["create"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: traffic-manager-connect
  namespace: {{ include "telepresence.namespace" . }}
  labels:
    {{- include "telepresence.labels" $ | nindent 4 }}
subjects:
{{- toYaml .Values.clientRbac.subjects | nindent 0}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  name: traffic-manager-connect
  kind: Role

{{- end }}
