# @TEMPLATE@
---
kind: Service
apiVersion: v1
metadata:
  name: httptest
spec:
  selector:
    pod: httptest
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: httptest
  labels:
    pod: httptest
spec:
  containers:
  - name: httptest
    image: {{image "../../Dockerfile"}}
    ports:
    - containerPort: 80
