# This should be the minimum RBAC that is needed for users (not operators) to
# use telepresence.  These objects are used in a portion of our tests to
# determine if we have changed the minimal rbac profile. If you need to change
# this file, you must also change it in the docs.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: telepresence-test-developer
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: telepresence-role
rules:
- apiGroups:
  - ""
  resources: ["services", "pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups:
    - ""
  resources: ["configmaps"]
  verbs: ["get", "update"]
  resourceNames: ["telepresence-agents"]
- apiGroups:
  - ""
  resources: ["pods/portforward"]
  verbs: ["create"]
- apiGroups:
  - "apps"
  resources: ["deployments", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups:
  - "getambassador.io"
  resources: ["hosts", "mappings"]
  verbs: ["*"]
- apiGroups:
  - ""
  resources: ["endpoints"]
  verbs: ["get", "list"]
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources: ["clusterroles", "clusterrolebindings"]
  verbs: ["get", "list", "watch"]
- apiGroups:
  - ""
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: telepresence-clusterrolebinding
subjects:
- name: telepresence-test-developer
  kind: ServiceAccount
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  name: telepresence-role
  kind: ClusterRole
