---
apiVersion: v1
kind: Service
metadata:
  name: echo-w-agent
spec:
  type: ClusterIP
  selector:
    service: echo-w-agent
  ports:
    - name: proxied
      port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-w-agent
  labels:
    service: echo-w-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      service: echo-w-agent
  template:
    metadata:
      labels:
        service: echo-w-agent
    spec:
      containers:
        - name: echo
          image: jmalloc/echo-server
          ports:
            - containerPort: 8080
        - name: traffic-agent
          image: ko://github.com/telepresenceio/telepresence/v2/cmd/traffic
          args: ["agent"]
          ports:
            - name: http
              containerPort: 9900
          env:
            - name: LOG_LEVEL
              value: debug
            - name: AGENT_NAME
              value: echo-w-agent
            - name: APP_PORT
              value: "8080"
