---
apiVersion: v1
kind: Service
metadata:
  name: rs-echo
spec:
  type: ClusterIP
  selector:
    service: rs-echo
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-echo
  labels:
    service: rs-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      service: rs-echo
  template:
    metadata:
      labels:
        service: rs-echo
    spec:
      containers:
        - name: rs-echo
          image: jmalloc/echo-server
          ports:
            - containerPort: 8080
