{{- if not .Values.rbac.only }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "telepresence.fullname" . }}
  namespace: {{ include "telepresence.namespace" . }}
  labels:
    {{- include "telepresence.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
  - name: api
    port: 8081
    targetPort: api
  selector:
    {{- include "telepresence.selectorLabels" . | nindent 4 }}
---
{{- if .Values.agentInjector.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.agentInjector.name }}
  namespace: {{ include "telepresence.namespace" . }}
  labels:
    {{- include "telepresence.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: https
    port: 443
    targetPort: https
  selector:
    {{- include "telepresence.selectorLabels" . | nindent 4 }}
{{- end }}
{{- end }}
