gems:
  - jekyll-redirect-from

title: Telepresence
email: itamar@telepresence.io
author: "Datawire.io"
description: "Telepresence: a local development environment for a remote Kubernetes cluster"
keywords: "Telepresence, Kubernetes, microservices"

baseurl: ""
url: "https://telepresence.io" # the base hostname & protocol for your site
twitter_username: datawireio
github_username:  datawire

# use this to define the categories of your documentation
category-list:
  - "tutorials"
  - "discussion"
  - "howto"
  - "reference"

# optionally you can define icon for each category (for the sidebar)
# Doc42 uses Font Awesome
category-icons: [code, question-circle, code, expand]

# Build settings
markdown: kramdown
