name: 'Close stale issues and PR'
on:
  push:
    branches:
      - release/v2

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue is stale because it has been open 60 days with no activity. Remove stale label or comment, or this will be closed in 7 days.'
          stale-pr-message: 'This PR is stale because it has been open 30 days with no activity. Remove stale label or comment, or this will be closed in 14 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 7 days with no activity.'
          close-pr-message: 'This PR was closed because it has been stalled for 14 days with no activity.'
          days-before-issue-stale: 60
          days-before-pr-stale: 30
          days-before-issue-close: 7
          days-before-pr-close: 14
          operations-per-run: 800
          exempt-issue-labels: feature,friction
